[package]
name = "regressor"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "regressor"
crate-type = ["cdylib"]

[dependencies]
polars = {version =  "0.53.0", features = ["ndarray"]}
pyo3 = { version = "0.27.2", features = ["extension-module"]}
pyo3-polars = "0.26.0"
numpy = "0.27"
ndarray = { version = "0.17.2",features = ["serde"] }
ndarray-linalg = { version = "0.18.1", features = ["intel-mkl-static"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"

