[package]
name = "regressor-python"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "regressor"
crate-type = ["cdylib"]

[dependencies]
polars = {workspace=true}
pyo3 = { version = "0.27.2", features = ["extension-module"]}
pyo3-polars = "0.26.0"
numpy = "0.27"
ndarray = {workspace=true}
ndarray-linalg = {workspace=true}
serde = {workspace=true}
serde_json = {workspace=true}
regressor-rs = { path="../regressor-rs" }
