[package]
name = "regressor"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "Regressor"
crate-type = ["cdylib"]

[dependencies]
polars = {version =  "0.53.0", features = ["ndarray"]}
pyo3 = { version = "0.27.2", features = ["extension-module"]}
pyo3-polars = "0.26.0"
ndarray = "0.17.2"
ndarray-linalg = "0.18.1"

